### ISSUE TITLE
Works until i close terminal.

### ISSUE THREAD

**Issue by gusman21** [sopel-irc/sopel-imdb#6] opened 2020-07-10 01:40 UTC
launch terminal
sopel -d
.imdb in channel functions as intended.

<$someuser> .imdb rocky
<$somebot> [Movie] Title: Rocky | Year: 1976 | Rating: 8.1 | Tomatometer: 94% | Genre: Drama, Sport | Plot: A small-time boxer gets a supremely rare chance to fight a heavy-weight champion in a bout in which he strives to go the distance for his self-respect. | IMDB Link: http://imdb.com/title/tt0075148

close terminal window
<$someuser> .imdb go
<$somebot> Unexpected error ([Errno 5] Input/output error) from $someuser at 2020-07-09 21:30:27.049912. Message was: .imdb go

**Comment by RustyBower** [comment] 2020-07-10 01:57
I'm not able to reproduce this issue. Can you provide any relevant logs from sopel?

**Comment by gusman21** [comment] 2020-07-10 10:43
[2020-07-09 21:33:24,359] sopel.irc            ERROR    - ERROR received from server: Closing Link: $somebot[$somebothostname] (Quit: Closing)
[2020-07-09 21:33:42,150] sopel.bot            ERROR    - Unexpected error ([Errno 5] Input/output error) from $someuser at 2020-07-09 21:33:42.149971. Message was: .imdb go
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/home/user/.local/lib/python3.8/site-packages/sopel_modules/imdb/imdb.py", line 71, in imdb
    bot.say(run_omdb_query(params, bot.config.core.verify_ssl, bot.config.imdb.api_key, True))
  File "/home/user/.local/lib/python3.8/site-packages/sopel_modules/imdb/imdb.py", line 84, in run_omdb_query
    print(data)
OSError: [Errno 5] Input/output error

P.S. It worked a treat and then I upgraded to LinuxMint 20.

**Comment by RustyBower** [comment] 2020-07-23 06:48
Hrm. I've been tinkering around trying to reproduce this with no luck :(

**Comment by dgw** [comment] 2020-07-23 08:55
Is this only for the `imdb` plugin/command, or any Sopel command/function?

**Comment by gusman21** [comment] 2020-07-23 10:17
so far ONLY imdb.

**Comment by gusman21** [comment] 2020-07-23 10:34
See here. https://imgur.com/a/JHQAl78 while the terminal is open there is output from the .imdb command.

**Comment by dgw** [comment] 2020-07-23 22:57
Oh, it's caused by a `print` that was removed in 81b96ce5aaf62d2645b55b3c92686dbc9bdf61f7. If you upgrade the plugin to at least v1.1.2 or v1.2.0 it should be fixed.

**Comment by gusman21** [comment] 2020-07-24 14:43
fixed in 1.2.0. I literally only installed this 3 weeks ago. Glad it was that simple of a resolution.

Thanks.

**Comment by RustyBower** [comment] 2020-07-24 17:03
Thanks for the help on this @dgw <3

**Closed as completed by RustyBower** 2020-07-24 17:03 UTC
